### ISSUE TITLE
undefined undefined

### ISSUE THREAD

**Issue by pulkitjalan** [unimonkiez/icon-maker-loader#1]
I have added this as per the webpack configuration but when im console logging the icon, i am getting `undefined undefined`

Below is our webpack config

<img width="1063" alt="screen shot 2017-03-23 at 12 21 06" src="https://cloud.githubusercontent.com/assets/4124930/24247358/507bd778-0fc3-11e7-9bed-8702fcfeeee0.png">

I'm not fully clued up on webpack and npm, can you please help?

Thanks

**Comment by unimonkiez** [comment]
Hey,
which version of the package are you using?

**Comment by pulkitjalan** [comment]
I have just installed it, `"icon-maker-loader": "^0.1.12"`

**Comment by pulkitjalan** [comment]
Thanks for fixing that so quickly!

**Comment by pulkitjalan** [comment]
Hey,

I'm still struggling to get it working, i no longer get the `undefined undefined`, but now the icons are not displayed...

I inspected the element and there is a `span` with the class `icon-maker` and `icon-maker-ok`, `ok` being the name of the icon I'm an requesting. It has a `font-size` of `20px` however the span is `0x0`.

I am guessing this is because the css is never loaded. Is that right?

I checked the `icon-maker-loader` folder in `node_modules` and there is a `.tmp` directory with the font/css files, is that suppose to be loaded in some way?

Thanks

**Comment by unimonkiez** [comment]
You should export the css somehow.. you only applied `css-loader` to your css files, change it to `style-loader!css-loader` (style loader adds the css to your application at runtime).

**Comment by unimonkiez** [comment]
@pulkitjalan Working now?

**Comment by pulkitjalan** [comment]
Hey, sorry, i didnt get a chance to try it yesterday, just tried it now and yea that works :).

I am now getting a few errors from `webpack-isomorphic-tools`

```
[webpack-isomorphic-tools] [error] asset not found: .src/icons/ok.svg
```

and 

```
[0] [webpack-isomorphic-tools/plugin] [error] ReferenceError: self is not defined
[0]     at !../../../style-loader/addStyles.js.webpack-module:15:30
[0]     at !../../../style-loader/addStyles.js.webpack-module:10:47
[0]     at module.exports (!../../../style-loader/addStyles.js.webpack-module:32:68)
[0]     at Object.<anonymous> (./icon-maker.css.webpack-module:8:60)
[0]     at Module._compile (module.js:570:32)
[0]     at Object._module2.default._extensions.(anonymous function) [as .webpack-module] (/code/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:274:11)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0]     at Function.Module._load (module.js:438:3)
[0]     at Module.require (module.js:497:17)
```

But from a quick google it seems they are known issues with `webpack-isomorphic-tools` and i'll need to have a read and find a solution.

Thanks for your help with this. Really appreciate it.

**Comment by unimonkiez** [comment]
@pulkitjalan I don't know this tool, not a part of this boilerplate..
But looks like this tool is getting the path wrong cause `.src/icons/ok.svg` doesn't equal `./src/icons/ok.svg`.

Good luck though!
